# Generated by Django 5.0.1 on 2024-01-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
    ]
